/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Scrap.glb -m -i 
Files: ./public/models/Scrap.glb [1.42MB] > C:\Users\haydn\00_DEVELOPMENT\StarGame\Scrap-transformed.glb [190.5KB] (87%)
Author: Armin Rezaei (https://sketchfab.com/Armin2am)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toilet-paper-holder-88a70b8069c845f49b63425adebe468d
Title: Toilet Paper Holder
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Scrap(props) {
  const { nodes, materials } = useGLTF("/models/Scrap-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Line02_silver_0.geometry}
        material={materials.silver}
        position={[0.37, 1.022, 2.426]}
        scale={0.032}
        userData={{ name: "Line02_silver_0" }}
      />
      <mesh
        geometry={nodes.Arc01_glass_0.geometry}
        material={materials.glass}
        position={[2.794, -0.149, 2.381]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.032}
        userData={{ name: "Arc01_glass_0" }}
      />
      <mesh
        geometry={nodes.Tube01_papper1_0.geometry}
        material={materials.papper1}
        position={[2.59, -0.4, 2.434]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.032}
        userData={{ name: "Tube01_papper1_0" }}
      />
      <mesh
        geometry={nodes["Tube01_09_-_Default_0"].geometry}
        material={materials["09_-_Default"]}
        position={[2.59, -0.4, 2.434]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.032}
        userData={{ name: "Tube01_09 - Default_0" }}
      />
      <mesh
        geometry={nodes.Tube01_papper2_0.geometry}
        material={materials.papper2}
        position={[2.59, -0.4, 2.434]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.032}
        userData={{ name: "Tube01_papper2_0" }}
      />
    </group>
  );
}

useGLTF.preload("/models/Scrap-transformed.glb");
